### ISSUE TITLE
gtx 1080 memory overflow

### ISSUE THREAD

**Issue by X7Becka** [TonyLianLong/AnimeGAN.js#3]
While i try to make an image w/o resize i got an error and monitors blinks for a second.
Task manager shows 12GB VRAM overflow.
```Error encountered while generating image: Error: Failed to compile fragment shader.```
![image](https://user-images.githubusercontent.com/51074290/90267817-43a09900-de80-11ea-966c-2d34c77c4b09.png)

Most likely i'm already out of trends 👍 
Gotta wait for 3090

**Comment by TonyLianLong** [comment]
No, you're not. 12GB is still a large amount of memory. How large is your image? I guess tf.js uses more memory than tf with same amount of computation because it treats everything as graphics content.

**Comment by X7Becka** [comment]
Image size is arround 1000x1000

**Comment by TonyLianLong** [comment]
Then it's too large. I recommend that you have a try at the python version.
