### ISSUE TITLE
When I was making AnimeGANv2.js, there was a problem of model conversion

### ISSUE THREAD

**Issue by TachibanaYoshino** [TonyLianLong/AnimeGAN.js#4]
When I converted saved_model into tfjs, there was a problem. I think you might have encountered it. How did you solve it?
the xshell scripts is :
`CUDA_VISIBLE_DEVICES=0 tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --signature_name='custom_signature' --output_node_names="output" --saved_model_tags=serve ./Hayao_model-64 ./web_model`

the error infomation is:
`ValueError: Unsupported Ops in the model before optimization
MirrorPad
(base) Workstation:/ada/AnimeGAN_js$ `

The MirrorPad corresponds to the reflect mode of tf. pad  in TF.
Can you give me some help

**Comment by TonyLianLong** [comment]
In the Javascript code, I added a custom operator for it.

**Comment by TachibanaYoshino** [comment]
Yes, I saw your custom code. At the same time, I also found that [tensorflowjs](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) added mirrorPad operation in previous days. Thank you very much for your reply.
